- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with Aws"
    DURATION: 120hRS
    TRAINER: Sivakumar
  tasks:
  - name: print the variable
    debug:
      msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}