- name: variables from files
  hosts: web
  connection:  local
  vars_files:
  tasks:
  - name: print course information
    debug:
      msg: "course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER}}"