- name: variables 
  hosts: local
  connection:  local
  # vars: 
  # GREET: "PLAY"
  vars_files:
  - course.yaml
  # vars_prompt:
  #- name: GREET
  # prompt: enter the value
  #private: false
  tasks:
  - name: print the variable
    # vars:
    # GREET: "TASK"
    debug:
      msg: "hello from {{ GREET }}"


# commond line and args
# task level
# prompt
# play
